[package]
name = "elf_loader"
version = "0.7.0"
edition = "2024"
authors = ["wzhao <1207410841@qq.com>"]
readme = "README.md"
repository = "https://github.com/weizhiao/elf_loader"
keywords = ["elf", "unix", "loader", "async"]
categories = ["no-std", "os", "embedded", "asynchronous"]
license = "MIT/Apache-2.0"
description = "A pure-rust library for loading ELF dynamic libraries from both memory and files."
exclude = [".gitignore"]

[workspace]
members = ["mini-loader"]

[dependencies.libc]
version = "0.2.169"
default-features = false
optional = true

[dependencies.syscalls]
version = "0.6.18"
default-features = false
optional = true

[dependencies.elf]
version = "0.7.4"
default-features = false

[dependencies]
bitflags = "2.8.0"
cfg-if = '1.0'

[features]
default = []

# Enable support for filesystems
fs = ["dep:syscalls"]
# Use libc as the backend, otherwise directly use linux syscalls
use-libc = ["dep:libc"]
# Use the default implementation on platforms with mmap when loading ELF files
mmap = ["dep:syscalls"]
# Use the version information of symbols when resolving them.
version = []

[[example]]
name = "relocate"
required-features = ["fs", "mmap"]
