[package]
name = "elf_loader"
version = "0.3.0"
edition = "2021"
authors = ["wzhao <1207410841@qq.com>"]
readme = "README.md"
repository = "https://github.com/weizhiao/elf_loader"
keywords = ["elf", "unix", "loader"]
categories = ["no-std", "os", "embedded"]
license = "Apache-2.0"
description = "A lightweight, extensible, and high-performance library for loading ELF files."
exclude = [".gitignore"]

[workspace]
members = ["mini-loader"]

[dependencies.libc]
version = "0.2.162"
default-features = false
optional = true

[dependencies.elf]
version = "0.7.4"
default-features = false

[dependencies]
bitflags = "2.6.0"
cfg-if = '1.0'

[features]
default = []

# enable std
std = []
# enable default implementation on devices with mmap
mmap = ["dep:libc", "std"]
# activate specific versions of symbols for dynamic library loading
version = []
