[package]
name = "elf_loader"
version = "0.5.0"
edition = "2024"
authors = ["wzhao <1207410841@qq.com>"]
readme = "README.md"
repository = "https://github.com/weizhiao/elf_loader"
keywords = ["elf", "unix", "loader", "async"]
categories = ["no-std", "os", "embedded", "asynchronous"]
license = "MIT/Apache-2.0"
description = "A Rust library providing async loading interface to load and relocate ELF dynamic libraries from memory/files."
exclude = [".gitignore"]

[workspace]
members = ["mini-loader"]

[dependencies.libc]
version = "0.2.169"
default-features = false
optional = true

[dependencies.elf]
version = "0.7.4"
default-features = false

[dependencies]
bitflags = "2.8.0"
cfg-if = '1.0'

[features]
default = []

# enable std
std = []
# enable default implementation on devices with mmap
mmap = ["dep:libc", "std"]
# activate specific versions of symbols for dynamic library loading
version = []
