[package]
name = "elf_loader"
version = "0.1.0"
edition = "2021"
authors = ["wzhao <1207410841@qq.com>"]
readme = "README.md"
repository = "https://github.com/weizhiao/elf_loader"
keywords = ["elf", "unix", "loader"]
categories = ["no-std", "os", "embedded"]
license = "Apache-2.0"
description = "A lightweight, scalable, and high-performance library for loading ELF format files."
exclude = [".gitignore"]

[dependencies.nix]
version = '0.29'
default-features = false
features = ['mman']
optional = true

[dependencies.elf]
version = "0.7.4"
default-features = false

[dependencies]
bitflags = "2.6.0"
cfg-if = '1.0'

[features]
default = ["std"]

# enable std
std = []
# enable default implementation on devices with mmap
mmap = ["dep:nix", "std"]
# enable this when you need to use thread local storage
tls = []
# activate specific versions of symbols for dynamic library loading
version = []
